package schema

const (
	NodeInvalid       = ""
	NodeDocument      = "doc"
	NodeText          = "text"
	NodeLineBreak     = "br"
	NodeThematicBreak = "hr"
	NodeHeading       = "heading"
	NodeParagraph     = "paragraph"
	NodeBlockQuote    = "blockquote"
	NodeNotice        = "container_notice"
	NodeImage         = "image"
	NodeVideo         = "video"
	NodeAttachment    = "attachment"
	NodeEmbed         = "embed"
	NodeMention       = "mention"
	NodeCodeBlock     = "code_block"
	NodeBulletList    = "bullet_list"
	NodeOrderedList   = "ordered_list"
	NodeListItem      = "list_item"
	NodeChecklist     = "checkbox_list"
	NodeChecklistItem = "checkbox_item"
	NodeTable         = "table"
	NodeTableRow      = "tr"
	NodeTableHeader   = "th"
	NodeTableCell     = "td"
)
